### PR TITLE
CI: Switch Codecov to an organization-wide token (instead of a repo-specific token)

### PR DESCRIPTION
**Pull request by DilumAluthge**
I have performed the following steps:
1. I logged into Codecov, and I went to the Codecov settings for the `JuliaMath` organization, and I went to the section named "Global Upload Token"[^1], and I went to the subsection named "Global repository upload token", and I clicked the "Generate" button, and I copied the token to my clipboard.
2. I went to the organization settingsfor the `JuliaMath` GitHub organization, and I went to the "Secrets and variables" tab, and within that tab I went to the "Actions" sub-tab[^2], and then I created a new organization-wide GitHub Actions Secret named `CODECOV_TOKEN`.

[^1]: https://app.codecov.io/account/gh/JuliaMath/org-upload-token

[^2]: https://github.com/organizations/JuliaMath/settings/secrets/actions

### CODE REVIEW

**Review by oscardssmith — DISMISSED** [review]

**Comment by DilumAluthge** [comment]
Looks like it's working correctly.

**Comment by DilumAluthge** [comment]
I'm going to delete the repo-specific Codecov secret from this repo.

**Review by devmotion — COMMENTED** [review]
Wouldn't it be easier to just call the orgwide token `CODECOV_TOKEN`? Then copying the examples from the codecov-action README would just work, without having to know about the name of the orgwide token.

**Comment by DilumAluthge** [comment]
Yeah, probably. I was thinking that it would be useful to be able to distinguish between repo-specific tokens and organization-wide tokens, but maybe that's not too important.

**Comment by DilumAluthge** [comment]
Okay, I've renamed the organization-wide secret from `CODECOV_TOKEN_ORGWIDE` to `CODECOV_TOKEN`.

**Comment by DilumAluthge** [comment]
Oh, now that the organization-wide secret is named `CODECOV_TOKEN`, this PR has no changes.

**Pull request closed without merging**
