### PR TITLE
CI: Fix Codecov

### PR DESCRIPTION
**Pull request by oscardssmith**

### CODE REVIEW

**Review by devmotion — COMMENTED** [review]
The workflow config looks good. Based on the CI logs (https://github.com/JuliaMath/IntegerMathUtils.jl/actions/runs/7786813263/job/21232481397?pr=14#step:8:31) I assume you haven't added the token as a Github secret yet?

**Comment by oscardssmith** [comment]
That is correct. Do I want to add them to actions/repository secrets?

**Comment by devmotion** [comment]
Yes, as a new repository secret: https://docs.codecov.com/docs/adding-the-codecov-token#github-actions (these instructions use the token as an environment variable in CI, but one can just directly add it as `token`: https://github.com/codecov/codecov-action?tab=readme-ov-file#usage)

**Comment by DilumAluthge** [comment]
I personally would recommend that you keep `fail_ci_if_error: true`.

That way, if there is a problem with Codecov, you get notified immediately.

**Comment by oscardssmith** [comment]
yeah. I was trying to delete it to see if it would fix things. I'm very confused as to why this doesn't work but https://github.com/JuliaDSP/DSP.jl/pull/525 does. I'd be interested if you know what the difference is.

**Comment by DilumAluthge** [comment]
In order to get coverage for Julia packages, we rely on Codecov's support for `lcov.info` files. Maybe `v4` of their action broke support for `lcov.info` files?

For debugging, let's `find` all `lcov.info` files, and maybe `head` them to make sure they look correct.

**Comment by DilumAluthge** [comment]
From the logs:

```
error - 2024-02-05 20:32:55,223 -- Commit creating failed: {"error": "Server Error (500)"}
```

Is this a 500 error from the Codecov server or from the GitHub server?

Either way, 500 implies the problem is on the server's side, not our side.

**Comment by staticfloat** [comment]
The macOS build is successfully uploading.

**Comment by DilumAluthge** [comment]
It was probably a transient server-side error on the Codecov servers?

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
@devmotion Since we're already working on the CI config here, I wonder if this is a good opportunity to do the following:
1. Add a `finalize` job.
2. Set up GitHub Merge Queue on this repo.

**Comment by DilumAluthge** [comment]
(I can enable merge queue in the GitHub repo settings, when we are ready.)

**Comment by oscardssmith** [comment]
this is ready to merge, right?

**Comment by oscardssmith** [comment]
thanks for the help!

**Pull request merged**
